__all__ = [
           "cmdSetSystemVolume",
           "cmdSetPlayerVolume",
           "cmdSetJointStiffness",
           
           "cmdOpenHand",
           "cmdSetLifeState",
           
           "cmdInfo",
           "cmdHallo",
           "cmdSay",
           "cmdSitDown",
           "cmdStandUp",
           "cmdVelocityWalk",
           "cmdThaiChi",
           "cmdWipeFHead",
           "cmdRedBallTracker",
           "cmdChangeLang",
           "cmdFaceTracker",
           "cmdShakeHands",
           "cmdGangnamStyle",
           "cmdCaravanPalace",
           "cmdEvolutionDance",
           "cmdEyesOfTheTiger",
           "cmdVangelisDance",
           "cmdSetVolume",
           "ledAngry",
           "ledBlink",
           "ledCautious",
           "ledCircleEyes",
           "ledDisco",
           "ledFlash",
           "ledHappy",
           "ledLaugh",
           "ledMischievious",
           "ledThinking"
           ]