'''
Created on 26.08.2014

@author: hannes
'''

SYS_GET_INFO = "SYS_GET_INFO"
SYS_SEND_INFO="SYS_SEND_INFO"
SYS_CONNECT = "SYS_CONNECT"
SYS_DISCONNECT = "SYS_DISCONNECT"
SYS_SET_REQUIRED_DATA = "SYS_SET_REQUIRED_DATA"